# Deep Session 1주차 실습
- [Pytorch](#Pytorch)
  - [gpu 불러오기](#gpu-불러오기)
- [Class](#Class)
  - [Class 생성](#Class-생성)
  - [상속](#상속)
- [Tensor](#Tensor)
  - [Scalar](#Scalar)
  - [Vector](#Vector)
  - [Matrix](#Matrix)
  - [Tensor](#Tensor)
- [Tensor Manipulation](#Tensor-Manipulation)
  - [1D Array with PyTorch](#1D-Array-with-PyTorch)
  - [2D Array with PyTorch](#2D-Array-with-PyTorch)
  - [Broadcasting](#Broadcasting)
  - [Mean](#Mean)
  - [Sum](#Sum)
  - [Max and Argmax](#Max-and-Argmax)
  - [View](#View)
  - [Squeeze](#Squeeze)
  - [Unsqueeze](#Unsqueeze)
  - [Scatter (for one-hot encoding)](#Scatter-(for-one-hot-encoding))
  - [Casting](#Casting)
  - [Concatenation](#Concatenation)
  - [Stacking](#Stacking)
  - [Ones and Zeros Like](#Ones-and-Zeros-Like)
  - [In-place Operation](#In-place-Operation)

## <font color = "#CC3D3D">Pytorch</font>

In [1]:
import torch

### gpu 불러오기

In [2]:
if torch.cuda.is_available(): # GPU를 이용해 계산할 수 있는지 파악
    DEVICE = torch.device('cuda') # device에 GPU를 할당
else:
    DEVICE = torch.device('cpu') # device에 CPU를 할당

## <font color = "#CC3D3D">Class</font>

<img src='https://wikidocs.net/images/page/28/class_cookie.png'>
<font size=1>이미지 출처: https://wikidocs.net/28</font>

- **클래스**: 똑같은 무엇인가를 만들어내는 설계 도면
- **객체**: 클래스로 만든 피조물
- **인스턴스**: 클래스가 지시한대로 만든 값
- **메소드**: 클래스 안에 구현된 함수
- **객체 변수**: 객체에 생성되는 객체만의 변수
- **생성자**: 객체가 생성되는 시점에 자동으로 호출되는 메소드

### Class 생성

In [3]:
class Fourcal:
    def setdata(self, first, second): # 메소드
        self.first = first # 객체 변수 생성
        self.second = second
    def add(self):
        result = self.first + self.second
        return result

In [4]:
a = Fourcal() # 객체 생성
a.setdata(1,2)
a.add()

3

In [5]:
b = Fourcal()
b.add()

AttributeError: 'Fourcal' object has no attribute 'first'

In [6]:
class Fourcal:
    def __init__(self, first, second): # 생성자
        self.first = first
        self.second = second
    def add(self):
        result = self.first + self.second
        return result

In [7]:
a = Fourcal()

TypeError: __init__() missing 2 required positional arguments: 'first' and 'second'

In [8]:
a = Fourcal(1,2)
a.add()

3

In [9]:
b = Fourcal(5,7)
b.add()

12

In [10]:
print("a's first: ",a.first, ", b's first: ",b.first)

a's first:  1 , b's first:  5


### 상속

In [11]:
class Parent: # 부모 클래스
    def __init__(self, p1, p2):
        self.p1 = p1
        self.p2 = p2
    def act(self):
        pass

class Child(Parent): # 자식클래스 -> 부모 클래스 상속
    def __init__(self, c1):
        self.c1 = c1

In [12]:
c = Child(3)

In [13]:
c.c1

3

In [14]:
c.p1

AttributeError: 'Child' object has no attribute 'p1'

In [15]:
class Child(Parent): # 자식클래스 -> 부모 클래스 상속
    pass

In [16]:
c = Child(1,2)

In [17]:
c.p1

1

In [18]:
class Child(Parent):
    def __init__(self, p1, p2, c1):
        super(Child, self).__init__(p1,p2) # 다른 클래스 및 속성을 자동으로 불러옴
        self.c1 = c1
    def parent_act(self):
        super().act() # 부모 클래스의 메소드 사용

In [19]:
c = Child(2,3,5)

In [20]:
print(c.p1, c.p2, c.c1)

2 3 5


In [21]:
c.parent_act()

## <font color = "#CC3D3D">Tensor</font>
<img src='http://aispiration.com/deep-learning/fig/tensor.jpg'>
<font size=1>이미지 출처: http://aispiration.com/deep-learning/tensorflow-data-structure.html</font>

### Scalar
상수(하나의 값을 표현할 때 1개의 수치로 표현)

In [22]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [23]:
scalar2 = torch.tensor([3.])    
print(scalar2)

tensor([3.])


사칙연산 수행가능(+, -, *, /)

In [24]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [25]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [26]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [27]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


메소드 사용하여 사칙연산 가능

In [28]:
torch.add(scalar1, scalar2)

tensor([4.])

In [29]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [30]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [31]:
torch.div(scalar1, scalar2)

tensor([0.3333])

### Vector
하나의 값을 표현할 때 2개 이상의 수치로 표현

In [32]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [33]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


사칙연산 가능(element-wise)

In [34]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [35]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [36]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [37]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


메소드 이용하여 사칙연산 가능

In [38]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [39]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [40]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [41]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

벡터 내적 연산 가능(`torch.dot()`, `torch.matmul()`)

In [42]:
torch.dot(vector1, vector2)

tensor(32.)

In [43]:
torch.matmul(vector1, vector2)

tensor(32.)

### Matrix
2개 이상의 벡터 값을 통합해 구성된 값

In [44]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [45]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


사칙연산 가능(element-wise)

In [46]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [47]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [48]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [49]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


메소드를 이용하여 사칙연산 가능

In [50]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [51]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [52]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [53]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

행렬곱 연산 가능(`torch.matmul()`, `torch.mm()`)
- `torch.dot()`은 벡터 내적 계산만 가능
- `torch.mm()`은 행렬만 가능

In [54]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

In [55]:
torch.mm(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

### Tensor
2차원 이상의 배열

In [56]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [57]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


사칙연산 가능(element-wise)

In [58]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [59]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [60]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [61]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


메소드를 이용하여 사칙연산 가능

In [62]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [63]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [64]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [65]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

텐서곱 연산 가능(동일 차원 행렬 간 행렬 곱)

In [66]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

## <font color = "#CC3D3D">Tensor Manipulation

### 1D Array with PyTorch

In [67]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [68]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Indexing
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [69]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [70]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [71]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [72]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [73]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mean

In [74]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [75]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [76]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [77]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [78]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [79]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [80]:
print(t.max()) # max 한 개의 값 반환

tensor(4.)


In [81]:
print(t.max(dim=0)) # dim을 주면 argmax도 같이 내보내준다.
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [82]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [83]:
t.argmax() # max인 값의 위치(index)

tensor(3)

### View
numpy 에서의 reshape와 같은 역할<br>
shape 바꿔줌

In [84]:
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [85]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [86]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze
쥐어 짜다. 1D로 바꿔준다.

In [87]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [88]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze
squeeze를 반대로

In [89]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [90]:
print(ft.unsqueeze(0)) # dim=0, dimension 0에 1을 넣어
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [91]:
print(ft.view(1, -1)) # unsqueeze(0)
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [92]:
print(ft.unsqueeze(1)) # dim=1, dimension 1에 1을 넣어
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [93]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Scatter (for one-hot encoding)

In [94]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [95]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting
type 변환

In [96]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [97]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [98]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [99]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

In [100]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [101]:
print(torch.cat([x, y], dim=0)) # dim 0이 늘어남
print(torch.cat([x, y], dim=1)) # dim 1이 늘어남

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
concatenate 편리하게 이용

In [102]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [103]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [104]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [105]:
print(torch.cat([x.unsqueeze(1), y.unsqueeze(1), z.unsqueeze(1)], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Ones and Zeros Like

In [106]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [107]:
print(torch.ones_like(x)) # 똑같은 shape로 만듦
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [108]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [109]:
print(x.mul(2.)) # 실행 결과가 변수에 저장되지 않음
print(x)
print(x.mul_(2.)) # _ 추가 시, 메모리에 새로 선언하지 않고 정답값에 바로 넣음
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
